parameters:
    penfold_geolocation.class:         Penfold\Bundle\GoogleGeolocationBundle\Geolocation\Google
    penfold_geolocation.url:           https://maps.googleapis.com/maps/api/geocode
    penfold_geolocation.format: json

services:
    penfold_geolocation:
        class:     %penfold_geolocation.class%
        arguments: [%penfold_geolocation.url%, %penfold_geolocation.format%]
